version: "2.1"
services:
  kdenlive:
    image: lscr.io/linuxserver/kdenlive:latest
    container_name: kdenlive
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
      - SUBFOLDER=/ #optional
    volumes:
      - /home/smaluish/docker/docker-config/kdenlive:/config
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb" #optional
    restart: unless-stopped
